import type { Field } from "./types";

const grassField: Field = {
    userCanStep: true,
    userCanJumpOver: false,
    type: "grass",
    bgColor: "bg-green-700",
};

const wallField: Field = {
    userCanStep: false,
    userCanJumpOver: false,
    type: "wall",
    bgColor: "bg-gray-700",
};

const rockField: Field = {
    userCanStep: false,
    userCanJumpOver: true,
    type: "rock",
    bgColor: "bg-gray-400",
};

const secretField: Field = {
    userCanStep: true,
    userCanJumpOver: false,
    type: "secret",
    onStep: () => {
        console.log("You found a secret!");
    },
    bgColor: "bg-yellow-300",
};

export default [
    [
        [
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            wallField,
            rockField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            wallField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
        ],
        [
            grassField,
            grassField,
            grassField,
            secretField,
            grassField,
            grassField,
            grassField,
            grassField,
            grassField,
            secretField,
        ],
    ],
];
